version: "3.2"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    volumes:
      - /media/hddext4/Docker/elasticsearch/:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/conf/elasticsearch.yml
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    restart: always

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.0
    labels:
      - traefik.frontend.rule=Host:kibana.stoicatedy.ovh
      - traefik.port=5601
      - traefik.frontend.auth.forward.address=https://auth.stoicatedy.ovh/api/verify?rd=https://auth.stoicatedy.ovh?rd=https://kibana.stoicatedy.ovh
      - traefik.frontend.headers.customRequestHeaders=X-Original-URI:kibana.stoicatedy.ovh
      - traefik.frontend.headers.customRequestHeaders=X-Original-URL:https://kibana.stoicatedy.ovh
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KIBANA_ELASTICSEARCH_URL=kibana.stoicatedy.ovh
    networks:
      - default
    restart: always

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.0 # must match elasticsearch image
    volumes:
      - /media/hdd/Docker/filebeat/:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log/:/var/log/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - elasticsearch
    environment:
      - setup.kibana.host=172.28.0.4:5601
    networks:
      - default
    restart: always
    user: root

  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:6.6.0
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    depends_on:
      - elasticsearch
    environment:
      - setup.kibana.host=172.28.0.4:5601
    networks:
      - default
    restart: always
    user: root

networks:
  default:
    external:
      name: web
