filebeat.inputs:
  - type: docker
    containers.ids:
      - "*"

# - module: traefik
#   access:
#     enabled: true
#     var.paths: ["/var/log/traefik/access.log*"]

# - type: log
#   paths:
#   - /var/log/traefik/*.json
#   json.keys_under_root: true
#   json.add_error_key: true
#   fields_under_root: true
#   fields:
#     tags: ['json','traefik']
#     project: traefik
#     source: traefik

# - type: log
#   paths:
#   - /var/log/traefik/*.json
#   json.keys_under_root: true
#   json.add_error_key: true
#   fields_under_root: true
#   fields:
#     tags: ['json','traefik']
#     project: traefik
#     source: traefik

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       templates:
#       - condition:
#           contains:
#             docker.container.image: elasticsearch
#         config:
#         - module: elasticsearch
#           log:
#             enabled: true
#             var.paths:
#             - /var/lib/docker/containers/${data.docker.container.id}/*.log

filebeat.modules:
  - module: traefik
    access:
      enabled: true
      var.paths: ["/var/log/traefik/access.log*"]
  - module: system
    syslog:
      enabled: true
      var.paths: ["/var/log/syslog*"]
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log*"]

processors:
  # decode the log field (sub JSON document) if JSONencoded, then maps it's fields to elasticsearch fields
  - decode_json_fields:
      fields: ["log"]
      target: ""
      # overwrite existing target elasticsearch fields while decoding json fields
      overwrite_keys: true
  - add_docker_metadata: ~

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:
  # if your kibana is local you can change it to 127.0.0.1:80
  host: "kibana:5601"
  protocol: "http"

output.elasticsearch:
  # if your elasticsearch is local you can change it to 127.0.0.1:9200
  hosts: ["elasticsearch:9200"]
  template:
    name: "docker"
    overwrite: false
  protocol: "http"

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.to_files: false
logging.to_syslog: false
