version: "2"
services:
  filebrowser:
    container_name: samba
    image: dperson/samba
    restart: always
    volumes:
      - /media/hddext4/FileServer/:/mount
    ports:
      - 139:139
      - 445:445
    command: >
      -s "users;/mount;yes;no;yes;admin;admin;admin;asd"
      -u "admin;admin" 

networks:
  default:
    external:
      name: web
