logs_level: info

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml

session:
  secret: test
  domain: stoicatedy.ovh

storage:
  local:
    path: /etc/authelia/storage

totp:
  issuer: stoicatedy.ovh

access_control:
  default_policy: deny
  rules:
    - domain: "*.stoicatedy.ovh"
      policy: two_factor

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

notifier:
  filesystem:
    filename: /tmp/authelia/notification.txt
