version: "3"

services:
  traefik:
    image: traefik
    command: >
      --docker
      --accesslog.filePath=/var/log/traefik/access.log
      --logLevel=INFO
      --insecureskipverify
      --defaultentrypoints=http,https
      --entryPoints=Name:https\ Address::443\ TLS
      --entryPoints=Name:http\ Address::80\ Redirect.EntryPoint:https
      --acme
      --acme.storage=/acme.json
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.email=stoicatedy@gmail.com
      --acme.onHostRule=true
      --acme.domains='stoicatedy.ovh'
      --acme.dnsChallenge.provider=cloudflare
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./acme.json:/acme.json
      - /var/log/traefik/:/var/log/traefik/
    container_name: traefik
    labels:
      - traefik.frontend.auth.forward.address=https://auth.stoicatedy.ovh/api/verify?rd=https://auth.stoicatedy.ovh?rd=https://kibana.stoicatedy.ovh
      - traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:max-age=63072000; includeSubDomains; preload
    networks:
      - default
    env_file: ./env.txt
    restart: always

networks:
  default:
    external:
      name: web
